### ISSUE TITLE
Feature: Telegram使用at元素時盡可能使用username & nickname

### ISSUE THREAD

**Issue by qilincai** [koishijs/koishi#1240]
### Describe the problem related to the feature request

目前tg平台使用at元素會直接userid作為inner text去at

`[123456789](tg://user?id=123456789)`

但TG軟件中inner text優先度為
1.有username優先使用username作為內部文字
`[username](tg://user?id=123456789)`
2.若sender對receiver的有設定nickname，則使用此nickname
3.若無則使用receiver的nickname
`[nickname](tg://user?id=123456789)`

### Describe the solution you'd like

at元素轉換後的inner text可以盡可能接近TG原平台邏輯

就我所知TG原本提供的api應該是無法用userid直接獲得username & nickname這些資訊

但像userid等於sender這些資訊已知的情況還是希望支持按照原邏輯去at

### Describe alternatives you've considered

目前我自己是簡單暴力把用戶username & nickname記到DB來at

但不保證at時的資料和實際資料一致

### Additional context

沒，就想提個小優化

**Comment by MaikoTan** [comment]
Yes, you're right. Since there isn't an API to obtain the user data by the user ID in Telegram, this can only be achieved by a local cache of user IDs and user names.

### Use the `name` field in `<at>` element

As you might aware, the `<at>` element includes a field `name` to specify the name when you are mentioning someone:

```html
<at id="12345678" name="Shigma" />
```

So the next question is: how could we store the names for every users.

### No databases for adapters

Koishi is based on [Satori](https://github.com/satorijs/satori), which is an independent protocol for ChatBots. We CANNOT or SHOULD NOT bundle a database onto it. Otherwise that would make other implementations hard to be implemented.

As for Koishi itself, well, that depends. But since Koishi is completely plug-and-play-ish, we also cannot predict that users have their databases installed. And even you put it aside, it is also weird to make a massive records into Koishi itself.

### What about a new plugin?

It is not surprisingly that you could easily achieve this by the powerful event system of Koishi, all you need is to register listeners:

```ts
// Store user data on some events
ctx.on('message', (session) => {
  if (session.sender) {
    // store user data
  }
})

// Modify content to send before actually sending it!
ctx.before('send', (session) => {
  // search for <at> element and then add name attribute onto it
})
```

As you can see, you could bundle these pieces of code into a new plugin, not really need to change Koishi itself but voilà!

------

<details>

<summary>譯文來自 ChatGPT（點選以檢視）</summary>

是的，你說得對。由於在Telegram中沒有API可以通過使用者ID來獲取使用者數據，這只能通過本地緩存使用者ID和使用者名稱來實現。

### 使用`<at>`元素中的`name`字段

正如你可能已經了解的那樣，`<at>`元素包括一個`name`字段，用於在提及某人時指定名稱：

```html
<at id="12345678" name="Shigma" />
```

那麼接下來的問題是：我們如何為每個使用者存儲名稱。

### 沒有適配器的數據庫

Koishi基於[Satori](https://github.com/satorijs/satori)，這是一個獨立的ChatBot協議。我們不能或者不應該將數據庫捆綁到其中。否則，這將使其他實現難以實現。

至於Koishi本身，那就視情況而定。但由於Koishi是完全即插即用的，我們也無法預測使用者是否安裝了數據庫。即使你將它放在一邊，將大量記錄添加到Koishi本身也有些奇怪。

### 新插件怎麼樣？

毫不奇怪，你可以藉助Koishi強大的事件系統輕松實現這一目標，你只需要註冊監聽器：

```ts
// 在某些事件上存儲使用者數據
ctx.on('message', (session) => {
  if (session.sender) {
    // 存儲使用者數據
  }
})

// 在實際發送之前修改要發送的內容！
ctx.before('send', (session) => {
  // 查找<at>元素，然後在其中添加name屬性
})
```

正如你所看到的，你可以將這些代碼片段捆綁到一個新的插件中，而無需真正更改Koishi本身，但妙不可言！

</details>

**Comment by shigma** [comment]
如上所述，最好的办法是在发送 at 时带上 name。telegram 适配器显然不应该以性能和占用为代价存储每一位用户的信息，但如果收到消息，那么带上 name 的成本不高。

**Comment by qilincai** [comment]
got it
