### ISSUE TITLE
Bug: 数据库操作只能插入，不能删除修改

### ISSUE THREAD

**Issue by 15015070064** [koishijs/koishi#854]
### Describe the bug

![image](https://user-images.githubusercontent.com/40047545/203911063-39f1ede1-2573-4c2e-955a-1446da407f29.png)

使用的是mongodb，能插入数据成功，但是只能插入, 不能修改和删除。点击删除和修改也提示修改成功但是实际没效果。

### Steps to reproduce

1.使用mongodb
2.界面插入一条数据
3. 检查数据库是否插入成功
4. 界面上修改某条数据的某个字段或者删除某条数据
5. 检查数据库

### Expected behavior

1.数据插入成功
2.数据能修改成功

### Screenshots

没有报错日志，界面上显示操作成功

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version: 
OS: WINDOWS 10
Platform: sanbox
node version: 16.15.1
koishio version: 4.10.3

**Comment by MaikoTan** [comment]
Hello, @15015070064 .

I could not reproduce the bug that you reported. I have a Koishi Robot running with MongoDB as well, but I successfully insert, modify and delete lines in the Koishi Console Web page on every try.

In order to locate your problem, may you:

- Specify the platform you are running, especially in containers or not
- Write down your MongoDB version, also Koishi's mongo database plugin version
- Check your logs if there are errors (both web page and terminal)
- Check your MongoDB logs if there are connections and operations.

**Comment by 15015070064** [comment]
> Hello, @15015070064 .
> 
> I could not reproduce the bug that you reported. I have a Koishi Robot running with MongoDB as well, but I successfully insert, modify and delete lines in the Koishi Console Web page on every try.
> 
> In order to locate your problem, may you:
> 
> * Specify the platform you are running, especially in containers or not
> * Write down your MongoDB version, also Koishi's mongo database plugin version
> * Check your logs if there are errors (both web page and terminal)
> * Check your MongoDB logs if there are connections and operations.

1. i try to run the mongodb in Windows 10,  whatever if the containers or local, the result is same
2. MongoDB version is 
![image](https://user-images.githubusercontent.com/40047545/204121338-a2e0ba25-484d-414b-96ee-6367f1270e02.png)
3. there are not error both web page and terminal
![image](https://user-images.githubusercontent.com/40047545/204121365-2ec63837-2b30-46cc-ad77-1899c69d30c3.png)
4.  there are not operations logs but connections logs
![image](https://user-images.githubusercontent.com/40047545/204121415-4a8b8a98-b69b-4674-aee7-a6ec69ed0168.png)

**Comment by 15015070064** [comment]
新版本解决了这个问题
